import { SITE_URL } from './cities'

export interface SeoPageConfig {
  slug: string
  /** API search params to embed results, or null for content-only pages */
  searchParams: Record<string, string> | null
  seo: {
    titleEn: string
    titleHe: string
    titleRu: string
    descEn: string
    descHe: string
    descRu: string
    keywords: string
  }
  /** Page content blocks (EN, HE, RU) */
  content: {
    h1En: string
    h1He: string
    h1Ru: string
    introEn: string
    introHe: string
    introRu: string
    bodyEn: string
    bodyHe: string
    bodyRu: string
  }
}

// ── Hebrew keyword landing pages ────────────────────────────────
const HEBREW_PAGES: SeoPageConfig[] = [
  {
    slug: 'naarot-livui',
    searchParams: null,
    seo: {
      titleEn: 'Escort Girls Israel — Tahles Directory',
      titleHe: 'נערות ליווי בישראל — מאגר Tahles',
      titleRu: 'Девушки по вызову Израиль — Каталог Tahles',
      descEn: 'The largest directory of escort girls in Israel. 67+ verified profiles with real photos, reviews, and direct WhatsApp contact.',
      descHe: 'המאגר הגדול ביותר של נערות ליווי בישראל. 67+ פרופילים מאומתים עם תמונות אמיתיות, ביקורות ו-WhatsApp ישיר.',
      descRu: 'Крупнейший каталог девушек по вызову в Израиле. 67+ проверенных анкет с реальными фото и прямым WhatsApp.',
      keywords: 'נערות ליווי, נערות ליווי בישראל, escort girls israel, Tahles, מאגר נערות ליווי',
    },
    content: {
      h1En: 'Escort Girls in Israel',
      h1He: 'נערות ליווי בישראל',
      h1Ru: 'Девушки по вызову в Израиле',
      introEn: 'Tahles is Israel\'s largest and most trusted escort directory with verified profiles, real photos, and direct contact.',
      introHe: 'Tahles הוא המאגר הגדול והאמין ביותר של נערות ליווי בישראל עם פרופילים מאומתים, תמונות אמיתיות וקשר ישיר.',
      introRu: 'Tahles — крупнейший и самый надёжный каталог эскорт-услуг в Израиле с проверенными анкетами и реальными фото.',
      bodyEn: 'Browse profiles from Tel Aviv, Haifa, Jerusalem, and all major Israeli cities. Every profile is verified with real photos, ratings, and direct WhatsApp numbers. Search by city, age, ethnicity, service type, and price range. Tahles updates daily with new profiles and reviews.',
      bodyHe: 'חפש פרופילים מתל אביב, חיפה, ירושלים וכל הערים הגדולות בישראל. כל פרופיל מאומת עם תמונות אמיתיות, דירוגים ומספרי WhatsApp ישירים. חפש לפי עיר, גיל, מוצא, סוג שירות וטווח מחירים. Tahles מתעדכן יומיומית.',
      bodyRu: 'Ищите анкеты из Тель-Авива, Хайфы, Иерусалима и всех крупных городов Израиля. Каждый профиль проверен с реальными фото, рейтингами и прямыми номерами WhatsApp. Поиск по городу, возрасту, этносу, типу услуг и цене.',
    },
  },
  {
    slug: 'sheruti-livui',
    searchParams: null,
    seo: {
      titleEn: 'Escort Services Israel — Tahles Directory',
      titleHe: 'שירותי ליווי בישראל — מאגר Tahles',
      titleRu: 'Эскорт услуги Израиль — Каталог Tahles',
      descEn: 'Premium escort services across Israel. Verified profiles, real photos, direct contact. The most honest escort directory.',
      descHe: 'שירותי ליווי פרמיום בכל רחבי ישראל. פרופילים מאומתים, תמונות אמיתיות, קשר ישיר. המאגר הכי אמין.',
      descRu: 'Премиальные эскорт-услуги по всему Израилю. Проверенные анкеты, реальные фото, прямой контакт.',
      keywords: 'שירותי ליווי, שירותי ליווי בישראל, escort services israel, ליווי ישראל',
    },
    content: {
      h1En: 'Escort Services in Israel',
      h1He: 'שירותי ליווי בישראל',
      h1Ru: 'Эскорт услуги в Израиле',
      introEn: 'Find premium escort services across all of Israel. Tahles aggregates verified profiles from multiple sources for maximum transparency.',
      introHe: 'מצא שירותי ליווי פרמיום בכל רחבי ישראל. Tahles מאגד פרופילים מאומתים ממקורות מרובים לשקיפות מקסימלית.',
      introRu: 'Найдите премиальные эскорт-услуги по всему Израилю. Tahles агрегирует проверенные анкеты из нескольких источников.',
      bodyEn: 'Whether you\'re looking for incall or outcall services, VIP companions, massage, or dating experiences — Tahles covers it all. Our directory features verified profiles with quality scores, real reviews, and multiple contact methods including WhatsApp.',
      bodyHe: 'בין אם אתה מחפש שירות בדירה, שירות עד הבית, ליווי VIP, עיסוי או חוויות דייטינג — Tahles מכסה הכל. המאגר שלנו כולל פרופילים מאומתים עם ציוני איכות, ביקורות אמיתיות ומספר דרכי קשר כולל WhatsApp.',
      bodyRu: 'Ищете ли вы приём у себя, выезд на дом, VIP сопровождение, массаж или свидания — Tahles охватывает всё. Наш каталог содержит проверенные анкеты с оценками качества и реальными отзывами.',
    },
  },
  {
    slug: 'livui-israel',
    searchParams: null,
    seo: {
      titleEn: 'Escort Israel — The Complete Directory | Tahles',
      titleHe: 'ליווי ישראל — המאגר המלא | Tahles',
      titleRu: 'Эскорт Израиль — Полный каталог | Tahles',
      descEn: 'Complete escort directory for Israel. All cities, all categories, verified profiles with real photos.',
      descHe: 'מאגר ליווי מלא לישראל. כל הערים, כל הקטגוריות, פרופילים מאומתים עם תמונות אמיתיות.',
      descRu: 'Полный каталог эскорта для Израиля. Все города, все категории, проверенные анкеты с реальными фото.',
      keywords: 'ליווי ישראל, ליווי, escort israel, Israel escort directory',
    },
    content: {
      h1En: 'Escort Directory Israel',
      h1He: 'מאגר ליווי ישראל',
      h1Ru: 'Каталог эскорта Израиль',
      introEn: 'Tahles — the most complete and honest escort directory in Israel, covering every major city.',
      introHe: 'Tahles — מאגר הליווי השלם והאמין ביותר בישראל, מכסה כל עיר גדולה.',
      introRu: 'Tahles — самый полный и честный каталог эскорта в Израиле, охватывающий все крупные города.',
      bodyEn: 'From Tel Aviv to Eilat, Tahles provides comprehensive coverage with over 67 verified profiles. Each profile includes real photos, verified contact details, service descriptions, pricing, and user reviews. Our automated quality scoring system ensures the best profiles appear first.',
      bodyHe: 'מתל אביב ועד אילת, Tahles מספק כיסוי מקיף עם מעל 67 פרופילים מאומתים. כל פרופיל כולל תמונות אמיתיות, פרטי קשר מאומתים, תיאורי שירות, מחירים וביקורות משתמשים. מערכת ציוני האיכות האוטומטית שלנו מבטיחה שהפרופילים הטובים ביותר מופיעים ראשונים.',
      bodyRu: 'От Тель-Авива до Эйлата, Tahles обеспечивает полное покрытие с более чем 67 проверенными анкетами. Каждый профиль включает реальные фото, проверенные контакты, описания услуг, цены и отзывы.',
    },
  },
  {
    slug: 'naarot-livui-badarom',
    searchParams: { city: 'Beer Sheva' },
    seo: {
      titleEn: 'Escort Girls in Southern Israel — Beer Sheva, Ashdod, Eilat',
      titleHe: 'נערות ליווי בדרום ישראל — באר שבע, אשדוד, אילת',
      titleRu: 'Девушки по вызову на юге Израиля',
      descEn: 'Escort profiles in southern Israel: Beer Sheva, Ashdod, Ashkelon, Eilat. Verified with real photos.',
      descHe: 'נערות ליווי בדרום ישראל: באר שבע, אשדוד, אשקלון, אילת. מאומתות עם תמונות אמיתיות.',
      descRu: 'Анкеты эскорта на юге Израиля: Беэр-Шева, Ашдод, Ашкелон, Эйлат. Проверенные с реальными фото.',
      keywords: 'נערות ליווי בדרום, ליווי באר שבע, ליווי אשדוד, ליווי אילת, escort south israel',
    },
    content: {
      h1En: 'Escort in Southern Israel',
      h1He: 'נערות ליווי בדרום ישראל',
      h1Ru: 'Эскорт на юге Израиля',
      introEn: 'Browse verified escort profiles across southern Israel — Beer Sheva, Ashdod, Ashkelon, and Eilat.',
      introHe: 'חפש פרופילי ליווי מאומתים בדרום ישראל — באר שבע, אשדוד, אשקלון ואילת.',
      introRu: 'Ищите проверенные анкеты эскорта на юге Израиля — Беэр-Шева, Ашдод, Ашкелон и Эйлат.',
      bodyEn: 'The Negev and southern coast have a growing directory of verified companions on Tahles. Whether you\'re visiting Eilat for vacation or based in Beer Sheva, find real profiles with direct WhatsApp contact.',
      bodyHe: 'הנגב וחוף הדרום כוללים מאגר גדל של מלוות מאומתות ב-Tahles. בין אם אתה מבקר באילת לחופשה או גר בבאר שבע, מצא פרופילים אמיתיים עם WhatsApp ישיר.',
      bodyRu: 'В Негеве и на южном побережье растёт каталог проверенных компаньонов на Tahles. Найдите реальные анкеты с прямым WhatsApp.',
    },
  },
  {
    slug: 'naarot-livui-batsafon',
    searchParams: { city: 'Haifa' },
    seo: {
      titleEn: 'Escort Girls in Northern Israel — Haifa, Hadera, Krayot',
      titleHe: 'נערות ליווי בצפון ישראל — חיפה, חדרה, קריות',
      titleRu: 'Девушки по вызову на севере Израиля',
      descEn: 'Escort profiles in northern Israel: Haifa, Hadera, Krayot. Verified with real photos.',
      descHe: 'נערות ליווי בצפון ישראל: חיפה, חדרה, קריות. מאומתות עם תמונות אמיתיות.',
      descRu: 'Анкеты эскорта на севере Израиля: Хайфа, Хадера, Крайот. Проверенные с реальными фото.',
      keywords: 'נערות ליווי בצפון, ליווי חיפה, ליווי חדרה, ליווי קריות, escort north israel',
    },
    content: {
      h1En: 'Escort in Northern Israel',
      h1He: 'נערות ליווי בצפון ישראל',
      h1Ru: 'Эскорт на севере Израиля',
      introEn: 'Browse verified escort profiles across northern Israel — Haifa, Hadera, Krayot, and surrounding areas.',
      introHe: 'חפש פרופילי ליווי מאומתים בצפון ישראל — חיפה, חדרה, קריות והסביבה.',
      introRu: 'Ищите проверенные анкеты эскорта на севере Израиля — Хайфа, Хадера, Крайот.',
      bodyEn: 'Northern Israel offers diverse companion options through Tahles. From the port city of Haifa to the quiet neighborhoods of Hadera, find verified profiles with real photos and ratings.',
      bodyHe: 'צפון ישראל מציע מגוון אפשרויות ליווי דרך Tahles. מעיר הנמל חיפה ועד השכונות השקטות של חדרה, מצא פרופילים מאומתים עם תמונות אמיתיות.',
      bodyRu: 'Север Израиля предлагает разнообразный выбор через Tahles. От портового города Хайфы до Хадеры — найдите проверенные анкеты.',
    },
  },
  {
    slug: 'naarot-livui-bamerkaz',
    searchParams: { city: 'Tel Aviv' },
    seo: {
      titleEn: 'Escort Girls in Central Israel — Tel Aviv, Rishon, Bat Yam',
      titleHe: 'נערות ליווי במרכז ישראל — תל אביב, ראשון, בת ים',
      titleRu: 'Девушки по вызову в центре Израиля',
      descEn: 'Escort profiles in central Israel: Tel Aviv, Rishon LeZion, Bat Yam, Herzliya, Netanya. The largest selection.',
      descHe: 'נערות ליווי במרכז ישראל: תל אביב, ראשון לציון, בת ים, הרצליה, נתניה. המבחר הגדול ביותר.',
      descRu: 'Анкеты эскорта в центре Израиля: Тель-Авив, Ришон-ле-Цион, Бат-Ям, Герцлия, Нетания.',
      keywords: 'נערות ליווי במרכז, ליווי תל אביב, ליווי ראשון לציון, ליווי גוש דן, escort central israel',
    },
    content: {
      h1En: 'Escort in Central Israel',
      h1He: 'נערות ליווי במרכז ישראל',
      h1Ru: 'Эскорт в центре Израиля',
      introEn: 'Central Israel has the largest selection of verified escort profiles on Tahles — Tel Aviv, Rishon LeZion, Bat Yam, Herzliya, and Netanya.',
      introHe: 'למרכז ישראל יש את המבחר הגדול ביותר של פרופילי ליווי מאומתים ב-Tahles — תל אביב, ראשון לציון, בת ים, הרצליה ונתניה.',
      introRu: 'В центре Израиля самый большой выбор проверенных анкет на Tahles — Тель-Авив, Ришон-ле-Цион, Бат-Ям, Герцлия и Нетания.',
      bodyEn: 'The Gush Dan metropolitan area is home to the majority of profiles on Tahles. With direct WhatsApp contact and real photos, finding a verified companion in central Israel has never been easier.',
      bodyHe: 'מטרופולין גוש דן הוא הביתי של רוב הפרופילים ב-Tahles. עם WhatsApp ישיר ותמונות אמיתיות, מציאת מלווה מאומתת במרכז ישראל מעולם לא הייתה קלה יותר.',
      bodyRu: 'Столичный район Гуш-Дан — дом для большинства анкет на Tahles. С прямым WhatsApp и реальными фото найти проверенного компаньона в центре Израиля проще простого.',
    },
  },
  {
    slug: 'naarot-livui-gush-dan',
    searchParams: { city: 'Tel Aviv' },
    seo: {
      titleEn: 'Escort in Gush Dan — Tel Aviv Metropolitan Area',
      titleHe: 'נערות ליווי בגוש דן — מטרופולין תל אביב',
      titleRu: 'Эскорт в Гуш-Дане — Большой Тель-Авив',
      descEn: 'Escort directory for the Gush Dan area: Tel Aviv, Ramat Gan, Givatayim, Holon, Bat Yam. Verified profiles.',
      descHe: 'מאגר ליווי לאזור גוש דן: תל אביב, רמת גן, גבעתיים, חולון, בת ים. פרופילים מאומתים.',
      descRu: 'Каталог эскорта для района Гуш-Дан: Тель-Авив, Рамат-Ган, Гиватаим, Холон, Бат-Ям.',
      keywords: 'ליווי גוש דן, נערות ליווי גוש דן, escort gush dan, תל אביב ליווי',
    },
    content: {
      h1En: 'Escort in Gush Dan Metropolitan',
      h1He: 'נערות ליווי בגוש דן',
      h1Ru: 'Эскорт в Гуш-Дане',
      introEn: 'The Gush Dan area offers the most diverse selection of escorts in Israel. Browse verified profiles from Tel Aviv and surrounding cities.',
      introHe: 'אזור גוש דן מציע את המבחר המגוון ביותר של ליווי בישראל. חפש פרופילים מאומתים מתל אביב והערים הסמוכות.',
      introRu: 'Район Гуш-Дан предлагает самый разнообразный выбор эскорта в Израиле.',
      bodyEn: 'The greater Tel Aviv area includes Ramat Gan, Givatayim, Holon, Bat Yam, and more. Tahles covers all neighborhoods with verified profiles.',
      bodyHe: 'אזור תל אביב הגדול כולל את רמת גן, גבעתיים, חולון, בת ים ועוד. Tahles מכסה את כל השכונות עם פרופילים מאומתים.',
      bodyRu: 'Большой Тель-Авив включает Рамат-Ган, Гиватаим, Холон, Бат-Ям и другие. Tahles охватывает все районы.',
    },
  },
  {
    slug: 'livui-vip',
    searchParams: { sheet: 'vip' },
    seo: {
      titleEn: 'VIP Escort Israel — Premium Service | Tahles',
      titleHe: 'ליווי VIP ישראל — שירות פרמיום | Tahles',
      titleRu: 'VIP эскорт Израиль — Премиум сервис | Tahles',
      descEn: 'Premium VIP escort services in Israel. Top-rated companions with the highest quality scores.',
      descHe: 'שירותי ליווי VIP פרמיום בישראל. מלוות מדורגות עם ציוני האיכות הגבוהים ביותר.',
      descRu: 'Премиальные VIP эскорт-услуги в Израиле. Лучшие компаньоны с высшими оценками качества.',
      keywords: 'ליווי VIP, VIP escort israel, ליווי פרמיום, שירות ליווי VIP, premium escort',
    },
    content: {
      h1En: 'VIP Escort Services Israel',
      h1He: 'שירותי ליווי VIP בישראל',
      h1Ru: 'VIP эскорт услуги в Израиле',
      introEn: 'Tahles VIP profiles represent the highest-rated companions in Israel, with premium quality scores and verified reviews.',
      introHe: 'פרופילי VIP של Tahles מייצגים את המלוות בדירוג הגבוה ביותר בישראל, עם ציוני איכות פרמיום וביקורות מאומתות.',
      introRu: 'VIP профили Tahles представляют лучших компаньонов Израиля с высшими оценками качества.',
      bodyEn: 'VIP profiles on Tahles feature the best quality scores, most photos, video content, and verified reviews. These companions offer premium services across all major Israeli cities.',
      bodyHe: 'פרופילי VIP ב-Tahles כוללים את ציוני האיכות הטובים ביותר, הכי הרבה תמונות, תוכן וידאו וביקורות מאומתות. מלוות אלו מציעות שירותי פרמיום בכל הערים הגדולות בישראל.',
      bodyRu: 'VIP профили на Tahles имеют лучшие оценки качества, больше фото, видеоконтент и проверенные отзывы.',
    },
  },
  {
    slug: 'livui-24-7',
    searchParams: null,
    seo: {
      titleEn: '24/7 Escort Services Israel — Always Available | Tahles',
      titleHe: 'שירותי ליווי 24/7 בישראל — תמיד זמינות | Tahles',
      titleRu: 'Эскорт 24/7 Израиль — Всегда доступны | Tahles',
      descEn: 'Find available escorts 24/7 in Israel. Browse online profiles anytime, day or night.',
      descHe: 'מצא נערות ליווי זמינות 24/7 בישראל. חפש פרופילים מקוונים בכל שעה, יום ולילה.',
      descRu: 'Найдите доступный эскорт 24/7 в Израиле. Ищите онлайн-анкеты в любое время.',
      keywords: 'ליווי 24/7, escort 24 7, נערות ליווי זמינות, available escorts, ליווי בלילה',
    },
    content: {
      h1En: '24/7 Escort Services Israel',
      h1He: 'שירותי ליווי 24/7 בישראל',
      h1Ru: 'Эскорт услуги 24/7 в Израиле',
      introEn: 'Tahles directory is available around the clock. Browse, search, and contact verified escorts at any time.',
      introHe: 'מאגר Tahles זמין מסביב לשעון. חפש, גלה וצור קשר עם נערות ליווי מאומתות בכל שעה.',
      introRu: 'Каталог Tahles доступен круглосуточно. Ищите и связывайтесь с проверенными эскортами в любое время.',
      bodyEn: 'Whether it\'s day or night, Tahles connects you with verified companions across Israel. Our profiles include online status indicators so you can see who\'s currently available.',
      bodyHe: 'בין אם ביום או בלילה, Tahles מחבר אותך עם מלוות מאומתות בכל ישראל. הפרופילים שלנו כוללים חיוויי סטטוס מקוון כדי שתוכל לראות מי זמינה כרגע.',
      bodyRu: 'Днём или ночью, Tahles связывает вас с проверенными компаньонами по всему Израилю. Наши профили показывают статус онлайн.',
    },
  },
  {
    slug: 'livui-lamalon',
    searchParams: { sheet: 'outcall' },
    seo: {
      titleEn: 'Hotel Escort Israel — Outcall to Hotels | Tahles',
      titleHe: 'ליווי למלון בישראל — שירות עד המלון | Tahles',
      titleRu: 'Эскорт в отель Израиль — Выезд в отель | Tahles',
      descEn: 'Hotel escort services in Israel. Verified companions available for hotel visits across all major cities.',
      descHe: 'שירותי ליווי למלון בישראל. מלוות מאומתות זמינות לביקורי מלון בכל הערים הגדולות.',
      descRu: 'Эскорт в отель в Израиле. Проверенные компаньоны для визитов в отели по всем крупным городам.',
      keywords: 'ליווי למלון, hotel escort israel, ליווי לבית מלון, escort hotel visit, outcall hotel',
    },
    content: {
      h1En: 'Hotel Escort Services in Israel',
      h1He: 'שירותי ליווי למלון בישראל',
      h1Ru: 'Эскорт в отель в Израиле',
      introEn: 'Find verified escorts who offer hotel visit services across Israel. Perfect for tourists and business travelers.',
      introHe: 'מצא נערות ליווי מאומתות המציעות שירות למלון בכל ישראל. מושלם לתיירים ואנשי עסקים.',
      introRu: 'Найдите проверенных эскортов, которые предлагают визиты в отели по всему Израилю.',
      bodyEn: 'Tahles lists verified outcall escorts available for hotel visits in Tel Aviv, Jerusalem, Eilat, and all major cities. Each profile shows service type (incall/outcall/both) so you know exactly what\'s available.',
      bodyHe: 'Tahles מציג נערות ליווי מאומתות עם שירות עד הבית הזמינות לביקורי מלון בתל אביב, ירושלים, אילת וכל הערים הגדולות. כל פרופיל מציג סוג שירות כדי שתדע בדיוק מה זמין.',
      bodyRu: 'Tahles показывает проверенных эскортов с выездом, доступных для визитов в отели в Тель-Авиве, Иерусалиме, Эйлате и других городах.',
    },
  },
  {
    slug: 'livui-labayit',
    searchParams: { sheet: 'outcall' },
    seo: {
      titleEn: 'Home Visit Escort Israel — Outcall Service | Tahles',
      titleHe: 'ליווי לבית בישראל — שירות עד הבית | Tahles',
      titleRu: 'Эскорт на дом Израиль — Выезд на дом | Tahles',
      descEn: 'Home visit escort services in Israel. Verified companions who come to you. Real photos & direct contact.',
      descHe: 'שירותי ליווי עד הבית בישראל. מלוות מאומתות שמגיעות אליך. תמונות אמיתיות וקשר ישיר.',
      descRu: 'Эскорт на дом в Израиле. Проверенные компаньоны, которые приедут к вам. Реальные фото.',
      keywords: 'ליווי לבית, ליווי עד הבית, home visit escort, outcall escort israel, שירות ליווי עד הבית',
    },
    content: {
      h1En: 'Home Visit Escort in Israel',
      h1He: 'שירותי ליווי עד הבית בישראל',
      h1Ru: 'Эскорт на дом в Израиле',
      introEn: 'Browse verified escorts offering home visit (outcall) services across all Israeli cities on Tahles.',
      introHe: 'חפש נערות ליווי מאומתות המציעות שירות עד הבית בכל הערים בישראל ב-Tahles.',
      introRu: 'Ищите проверенных эскортов с выездом на дом по всем городам Израиля на Tahles.',
      bodyEn: 'Tahles makes it easy to find outcall companions in Israel. Filter profiles by city and service type to find escorts who provide home visits. All profiles are verified with real photos.',
      bodyHe: 'Tahles מקל על מציאת מלוות עם שירות עד הבית בישראל. סנן פרופילים לפי עיר וסוג שירות. כל הפרופילים מאומתים עם תמונות אמיתיות.',
      bodyRu: 'Tahles упрощает поиск компаньонов с выездом в Израиле. Фильтруйте анкеты по городу и типу услуг.',
    },
  },
  {
    slug: 'naarot-livui-meumtot',
    searchParams: { sheet: 'verified' },
    seo: {
      titleEn: 'Verified Escort Girls Israel — Real Photos Guaranteed',
      titleHe: 'נערות ליווי מאומתות בישראל — תמונות אמיתיות מובטחות',
      titleRu: 'Проверенные девушки Израиль — Гарантия реальных фото',
      descEn: 'Only verified escort profiles in Israel. Real photos, confirmed identity, trusted directory on Tahles.',
      descHe: 'רק פרופילי ליווי מאומתים בישראל. תמונות אמיתיות, זהות מאושרת, מאגר אמין ב-Tahles.',
      descRu: 'Только проверенные анкеты эскорта в Израиле. Реальные фото, подтверждённая личность.',
      keywords: 'נערות ליווי מאומתות, verified escorts israel, פרופילים מאומתים, ליווי מאומת, real photos escort',
    },
    content: {
      h1En: 'Verified Escort Profiles in Israel',
      h1He: 'נערות ליווי מאומתות בישראל',
      h1Ru: 'Проверенные анкеты эскорта в Израиле',
      introEn: 'Tahles prioritizes trust and honesty. Our verified profiles have been cross-checked for authentic photos and accurate information.',
      introHe: 'Tahles שם דגש על אמון ואמינות. הפרופילים המאומתים שלנו נבדקו צולבת לתמונות אותנטיות ומידע מדויק.',
      introRu: 'Tahles ставит приоритет на доверие и честность. Наши проверенные профили перекрёстно проверены.',
      bodyEn: 'Every verified profile on Tahles has been screened through our quality system. We aggregate data from multiple sources and flag profiles that meet our standards. The result: you can trust what you see.',
      bodyHe: 'כל פרופיל מאומת ב-Tahles עבר סינון דרך מערכת האיכות שלנו. אנו מאגדים נתונים ממקורות מרובים ומסמנים פרופילים שעומדים בסטנדרטים שלנו. התוצאה: אתה יכול לסמוך על מה שאתה רואה.',
      bodyRu: 'Каждый проверенный профиль на Tahles прошёл через нашу систему качества. Мы агрегируем данные из нескольких источников.',
    },
  },
  {
    slug: 'livui-diskruti',
    searchParams: null,
    seo: {
      titleEn: 'Discreet Escort Israel — Private & Confidential | Tahles',
      titleHe: 'ליווי דיסקרטי בישראל — פרטי וסודי | Tahles',
      titleRu: 'Дискретный эскорт Израиль — Конфиденциально | Tahles',
      descEn: 'Discreet escort services in Israel. Private profiles, direct WhatsApp contact, no intermediaries.',
      descHe: 'שירותי ליווי דיסקרטיים בישראל. פרופילים פרטיים, WhatsApp ישיר, ללא מתווכים.',
      descRu: 'Дискретные эскорт-услуги в Израиле. Приватные профили, прямой WhatsApp, без посредников.',
      keywords: 'ליווי דיסקרטי, discreet escort israel, ליווי פרטי, דירות דיסקרטיות, שירות ליווי דיסקרטי',
    },
    content: {
      h1En: 'Discreet Escort Services in Israel',
      h1He: 'שירותי ליווי דיסקרטיים בישראל',
      h1Ru: 'Дискретные эскорт-услуги в Израиле',
      introEn: 'Tahles ensures privacy and discretion. Direct WhatsApp contact means no intermediaries — just you and the verified companion.',
      introHe: 'Tahles מבטיח פרטיות ודיסקרטיות. WhatsApp ישיר אומר ללא מתווכים — רק אתה והמלווה המאומתת.',
      introRu: 'Tahles обеспечивает приватность и дискретность. Прямой WhatsApp — без посредников.',
      bodyEn: 'Every profile on Tahles features direct contact methods. No phone lines, no agencies in the middle. You contact companions directly via WhatsApp, ensuring maximum privacy.',
      bodyHe: 'כל פרופיל ב-Tahles כולל דרכי קשר ישירות. ללא קווים טלפוניים, ללא סוכנויות באמצע. אתה יוצר קשר ישיר עם מלוות דרך WhatsApp, מה שמבטיח פרטיות מקסימלית.',
      bodyRu: 'Каждый профиль на Tahles содержит прямые контакты. Никаких телефонных линий и агентств — вы связываетесь напрямую через WhatsApp.',
    },
  },
  {
    slug: 'madrich-livui',
    searchParams: null,
    seo: {
      titleEn: 'Escort Guide Israel — How to Choose Safely | Tahles',
      titleHe: 'מדריך ליווי בישראל — איך לבחור בבטחה | Tahles',
      titleRu: 'Гид по эскорту Израиль — Как выбрать безопасно | Tahles',
      descEn: 'Complete guide to choosing an escort in Israel. Safety tips, what to look for, and how Tahles helps.',
      descHe: 'מדריך מלא לבחירת שירות ליווי בישראל. טיפים לבטיחות, על מה לשים לב, ואיך Tahles עוזר.',
      descRu: 'Полный гид по выбору эскорта в Израиле. Советы безопасности и как Tahles помогает.',
      keywords: 'מדריך ליווי, escort guide, איך לבחור נערת ליווי, טיפים ליווי, escort tips',
    },
    content: {
      h1En: 'Guide to Choosing an Escort in Israel',
      h1He: 'מדריך לבחירת נערת ליווי בישראל',
      h1Ru: 'Гид по выбору эскорта в Израиле',
      introEn: 'Tahles helps you make informed decisions with verified profiles, real reviews, and quality scores.',
      introHe: 'Tahles עוזר לך לקבל החלטות מושכלות עם פרופילים מאומתים, ביקורות אמיתיות וציוני איכות.',
      introRu: 'Tahles помогает принимать обоснованные решения с проверенными анкетами и реальными отзывами.',
      bodyEn: 'Look for verified badges, read reviews, check the quality score, and always use direct WhatsApp contact. Tahles does the hard work of aggregating and verifying profiles so you don\'t have to.',
      bodyHe: 'חפש תגי אימות, קרא ביקורות, בדוק את ציון האיכות, ותמיד השתמש ב-WhatsApp ישיר. Tahles עושה את העבודה הקשה של איגוד ואימות פרופילים כדי שלא תצטרך.',
      bodyRu: 'Ищите значки верификации, читайте отзывы, проверяйте оценку качества и всегда используйте прямой WhatsApp. Tahles делает тяжёлую работу за вас.',
    },
  },
]

// ── Russian keyword landing pages ───────────────────────────────
const RUSSIAN_PAGES: SeoPageConfig[] = [
  {
    slug: 'eskort-izrail',
    searchParams: null,
    seo: {
      titleEn: 'Escort Israel — Verified Directory | Tahles',
      titleHe: 'אסקורט ישראל — מאגר מאומת | Tahles',
      titleRu: 'Эскорт Израиль — Проверенный каталог | Tahles',
      descEn: 'The largest verified escort directory in Israel. 67+ real profiles with photos and WhatsApp.',
      descHe: 'המאגר המאומת הגדול ביותר של אסקורט בישראל. 67+ פרופילים אמיתיים.',
      descRu: 'Крупнейший проверенный каталог эскорта в Израиле. 67+ реальных анкет с фото и WhatsApp.',
      keywords: 'эскорт израиль, eskort izrail, escort israel, проверенный эскорт, каталог эскорта',
    },
    content: {
      h1En: 'Escort Directory Israel',
      h1He: 'מאגר אסקורט ישראל',
      h1Ru: 'Каталог эскорта Израиль',
      introEn: 'Tahles is the most trusted escort directory in Israel with verified profiles and direct contact.',
      introHe: 'Tahles הוא מאגר האסקורט האמין ביותר בישראל עם פרופילים מאומתים וקשר ישיר.',
      introRu: 'Tahles — самый надёжный каталог эскорта в Израиле с проверенными анкетами и прямым контактом.',
      bodyEn: 'Browse profiles from all major Israeli cities with real photos, reviews, and quality scores.',
      bodyHe: 'חפש פרופילים מכל הערים הגדולות בישראל עם תמונות אמיתיות, ביקורות וציוני איכות.',
      bodyRu: 'Ищите анкеты из всех крупных городов Израиля с реальными фото, отзывами и оценками качества. Tahles ежедневно обновляется новыми профилями и отзывами.',
    },
  },
  {
    slug: 'devushki-po-vizovu',
    searchParams: null,
    seo: {
      titleEn: 'Call Girls Israel — Verified Profiles | Tahles',
      titleHe: 'נערות ליווי להזמנה בישראל | Tahles',
      titleRu: 'Девушки по вызову Израиль — Проверенные анкеты | Tahles',
      descEn: 'Verified call girls in Israel. Real photos, direct WhatsApp. Browse the largest directory.',
      descHe: 'נערות ליווי מאומתות להזמנה בישראל. תמונות אמיתיות, WhatsApp ישיר.',
      descRu: 'Проверенные девушки по вызову в Израиле. Реальные фото, прямой WhatsApp. Крупнейший каталог.',
      keywords: 'девушки по вызову, девушки по вызову израиль, call girls israel, вызов девушки',
    },
    content: {
      h1En: 'Call Girls in Israel',
      h1He: 'נערות ליווי להזמנה בישראל',
      h1Ru: 'Девушки по вызову в Израиле',
      introEn: 'Find verified call girls across all Israeli cities on Tahles.',
      introHe: 'מצא נערות ליווי מאומתות להזמנה בכל ערי ישראל ב-Tahles.',
      introRu: 'Найдите проверенных девушек по вызову во всех городах Израиля на Tahles.',
      bodyEn: 'Tahles features the largest collection of verified profiles in Israel with direct contact methods.',
      bodyHe: 'Tahles מציג את האוסף הגדול ביותר של פרופילים מאומתים בישראל עם דרכי קשר ישירות.',
      bodyRu: 'Tahles предлагает крупнейшую коллекцию проверенных анкет в Израиле с прямыми контактами. Поиск по городу, возрасту, этносу и типу услуг.',
    },
  },
  {
    slug: 'eskort-uslugi-izrail',
    searchParams: null,
    seo: {
      titleEn: 'Escort Services Israel — Premium Directory | Tahles',
      titleHe: 'שירותי אסקורט ישראל — מאגר פרמיום | Tahles',
      titleRu: 'Эскорт услуги Израиль — Премиум каталог | Tahles',
      descEn: 'Premium escort services across Israel. Verified profiles, real photos, direct contact.',
      descHe: 'שירותי אסקורט פרמיום בישראל. פרופילים מאומתים, תמונות אמיתיות, קשר ישיר.',
      descRu: 'Премиальные эскорт-услуги по всему Израилю. Проверенные анкеты, реальные фото, прямой контакт.',
      keywords: 'эскорт услуги, эскорт услуги израиль, eskort uslugi, premium escort services',
    },
    content: {
      h1En: 'Escort Services in Israel',
      h1He: 'שירותי אסקורט בישראל',
      h1Ru: 'Эскорт услуги в Израиле',
      introEn: 'Find premium escort services across Israel on Tahles.',
      introHe: 'מצא שירותי אסקורט פרמיום בישראל ב-Tahles.',
      introRu: 'Найдите премиальные эскорт-услуги по всему Израилю на Tahles.',
      bodyEn: 'Browse a variety of services including incall, outcall, massage, dating, and VIP companionship.',
      bodyHe: 'חפש מגוון שירותים כולל קבלה בדירה, שירות עד הבית, עיסוי, דייטינג וליווי VIP.',
      bodyRu: 'Ищите разнообразные услуги: приём у себя, выезд на дом, массаж, свидания и VIP сопровождение. Все анкеты проверены с реальными фото.',
    },
  },
  {
    slug: 'individualki-izrail',
    searchParams: { category: 'individual' },
    seo: {
      titleEn: 'Independent Escorts Israel — No Agency | Tahles',
      titleHe: 'נערות ליווי עצמאיות ישראל — ללא סוכנות | Tahles',
      titleRu: 'Индивидуалки Израиль — Без агентства | Tahles',
      descEn: 'Independent escorts in Israel — no agency, direct contact only. Verified profiles on Tahles.',
      descHe: 'נערות ליווי עצמאיות בישראל — ללא סוכנות, קשר ישיר בלבד. פרופילים מאומתים ב-Tahles.',
      descRu: 'Индивидуалки в Израиле — без агентства, только прямой контакт. Проверенные анкеты на Tahles.',
      keywords: 'индивидуалки израиль, individualki, independent escorts, без агентства, прямой контакт',
    },
    content: {
      h1En: 'Independent Escorts in Israel',
      h1He: 'נערות ליווי עצמאיות בישראל',
      h1Ru: 'Индивидуалки в Израиле',
      introEn: 'Browse independent escorts who work on their own — no agency, direct WhatsApp contact only.',
      introHe: 'חפש נערות ליווי עצמאיות שעובדות לבד — ללא סוכנות, קשר ישיר ב-WhatsApp בלבד.',
      introRu: 'Ищите индивидуалок, которые работают самостоятельно — без агентства, только прямой WhatsApp.',
      bodyEn: 'Independent profiles on Tahles are individually verified. Each companion manages their own profile and contacts directly.',
      bodyHe: 'פרופילים עצמאיים ב-Tahles מאומתים אישית. כל מלווה מנהלת את הפרופיל שלה ומקבלת פניות ישירות.',
      bodyRu: 'Индивидуальные профили на Tahles проверены лично. Каждый компаньон управляет своим профилем и принимает обращения напрямую.',
    },
  },
  {
    slug: 'massazh-izrail',
    searchParams: { q: 'massage' },
    seo: {
      titleEn: 'Massage Israel — Professional Services | Tahles',
      titleHe: 'עיסוי בישראל — שירותים מקצועיים | Tahles',
      titleRu: 'Массаж Израиль — Профессиональные услуги | Tahles',
      descEn: 'Professional massage services in Israel. Verified providers with real photos on Tahles.',
      descHe: 'שירותי עיסוי מקצועיים בישראל. ספקים מאומתים עם תמונות אמיתיות ב-Tahles.',
      descRu: 'Профессиональные услуги массажа в Израиле. Проверенные мастера с реальными фото на Tahles.',
      keywords: 'массаж израиль, massazh izrail, massage israel, профессиональный массаж, эротический массаж',
    },
    content: {
      h1En: 'Massage Services in Israel',
      h1He: 'שירותי עיסוי בישראל',
      h1Ru: 'Услуги массажа в Израиле',
      introEn: 'Find professional massage providers across Israel on Tahles.',
      introHe: 'מצא ספקי עיסוי מקצועיים בכל ישראל ב-Tahles.',
      introRu: 'Найдите профессиональных мастеров массажа по всему Израилю на Tahles.',
      bodyEn: 'Tahles features massage professionals offering various types of services across all major Israeli cities.',
      bodyHe: 'Tahles מציג מעסים מקצועיים המציעים סוגים שונים של שירותים בכל הערים הגדולות בישראל.',
      bodyRu: 'Tahles представляет профессиональных массажистов, предлагающих различные виды услуг во всех крупных городах Израиля.',
    },
  },
  {
    slug: 'luchshiy-eskort-izrail',
    searchParams: { sheet: 'vip' },
    seo: {
      titleEn: 'Best Escort Israel — Top Rated Profiles | Tahles',
      titleHe: 'הליווי הטוב ביותר בישראל — פרופילים מדורגים | Tahles',
      titleRu: 'Лучший эскорт Израиль — Топ анкеты | Tahles',
      descEn: 'The best-rated escort profiles in Israel. Top quality scores, most reviews, highest-rated companions.',
      descHe: 'הפרופילים הטובים ביותר של ליווי בישראל. ציוני איכות מובילים, הכי הרבה ביקורות.',
      descRu: 'Лучшие анкеты эскорта в Израиле. Высшие оценки качества, больше всего отзывов, лучшие компаньоны.',
      keywords: 'лучший эскорт израиль, best escort israel, топ эскорт, лучшие девушки, рейтинг эскорта',
    },
    content: {
      h1En: 'Best Escort in Israel',
      h1He: 'הליווי הטוב ביותר בישראל',
      h1Ru: 'Лучший эскорт в Израиле',
      introEn: 'Tahles ranks profiles by quality score — see the best-rated companions in Israel.',
      introHe: 'Tahles מדרג פרופילים לפי ציון איכות — ראה את המלוות המדורגות ביותר בישראל.',
      introRu: 'Tahles ранжирует профили по оценке качества — смотрите лучших компаньонов Израиля.',
      bodyEn: 'Our quality scoring system considers photos, reviews, verification status, contact methods, and profile completeness. The highest-rated profiles appear first.',
      bodyHe: 'מערכת ציוני האיכות שלנו מתחשבת בתמונות, ביקורות, סטטוס אימות, דרכי קשר ושלמות הפרופיל. הפרופילים בדירוג הגבוה ביותר מופיעים ראשונים.',
      bodyRu: 'Наша система оценки качества учитывает фото, отзывы, статус верификации, способы связи и полноту профиля. Лучшие анкеты показываются первыми.',
    },
  },
  {
    slug: 'eskort-tseni',
    searchParams: null,
    seo: {
      titleEn: 'Escort Prices Israel — Transparent Pricing | Tahles',
      titleHe: 'מחירי ליווי בישראל — מחירים שקופים | Tahles',
      titleRu: 'Цены эскорта Израиль — Прозрачные цены | Tahles',
      descEn: 'Transparent escort pricing in Israel. Compare prices, find profiles in your budget on Tahles.',
      descHe: 'מחירי ליווי שקופים בישראל. השווה מחירים, מצא פרופילים בתקציב שלך ב-Tahles.',
      descRu: 'Прозрачные цены эскорта в Израиле. Сравнивайте цены, находите анкеты в вашем бюджете на Tahles.',
      keywords: 'цены эскорта, eskort tseni, escort prices israel, מחירי ליווי, стоимость эскорта',
    },
    content: {
      h1En: 'Escort Prices in Israel',
      h1He: 'מחירי ליווי בישראל',
      h1Ru: 'Цены на эскорт в Израиле',
      introEn: 'Tahles shows transparent pricing for all profiles. Filter by price range to find companions within your budget.',
      introHe: 'Tahles מציג מחירים שקופים לכל הפרופילים. סנן לפי טווח מחירים כדי למצוא מלוות בתקציב שלך.',
      introRu: 'Tahles показывает прозрачные цены для всех анкет. Фильтруйте по ценовому диапазону.',
      bodyEn: 'Each profile on Tahles displays price ranges and detailed price tables by service type. Use our price filter to find profiles that match your budget.',
      bodyHe: 'כל פרופיל ב-Tahles מציג טווחי מחירים וטבלאות מחירים מפורטות לפי סוג שירות. השתמש בפילטר המחירים שלנו כדי למצוא פרופילים שמתאימים לתקציב שלך.',
      bodyRu: 'Каждый профиль на Tahles отображает ценовые диапазоны и подробные таблицы цен по типу услуг. Используйте наш ценовой фильтр.',
    },
  },
  {
    slug: 'vip-eskort-izrail',
    searchParams: { sheet: 'vip' },
    seo: {
      titleEn: 'VIP Escort Israel — Luxury Companions | Tahles',
      titleHe: 'VIP אסקורט ישראל — מלוות יוקרתיות | Tahles',
      titleRu: 'VIP эскорт Израиль — Элитные компаньоны | Tahles',
      descEn: 'VIP escort services in Israel. The most exclusive, highest-rated companions on Tahles.',
      descHe: 'שירותי VIP אסקורט בישראל. המלוות הבלעדיות ביותר ובדירוג הגבוה ביותר ב-Tahles.',
      descRu: 'VIP эскорт-услуги в Израиле. Самые эксклюзивные компаньоны с высшими рейтингами на Tahles.',
      keywords: 'VIP эскорт израиль, vip escort israel, элитный эскорт, VIP ליווי, luxury escort',
    },
    content: {
      h1En: 'VIP Escort Services Israel',
      h1He: 'שירותי VIP אסקורט בישראל',
      h1Ru: 'VIP эскорт услуги в Израиле',
      introEn: 'Tahles VIP tier features the highest-quality companions in Israel.',
      introHe: 'דרגת VIP של Tahles מציגה את המלוות באיכות הגבוהה ביותר בישראל.',
      introRu: 'Уровень VIP на Tahles представляет компаньонов высшего качества в Израиле.',
      bodyEn: 'VIP profiles feature more photos, video content, detailed service descriptions, and the highest quality scores.',
      bodyHe: 'פרופילי VIP כוללים יותר תמונות, תוכן וידאו, תיאורי שירות מפורטים וציוני איכות הגבוהים ביותר.',
      bodyRu: 'VIP профили содержат больше фото, видеоконтент, подробные описания услуг и высшие оценки качества.',
    },
  },
]

// ── English keyword landing pages ───────────────────────────────
const ENGLISH_PAGES: SeoPageConfig[] = [
  {
    slug: 'best-escort-directory-israel',
    searchParams: null,
    seo: {
      titleEn: 'Best Escort Directory Israel — Tahles #1 Aggregator',
      titleHe: 'מאגר הליווי הטוב ביותר בישראל — Tahles אגרגטור #1',
      titleRu: 'Лучший каталог эскорта Израиль — Tahles агрегатор №1',
      descEn: 'Tahles is the #1 escort directory in Israel. Verified profiles, real photos, quality scores, and direct WhatsApp contact.',
      descHe: 'Tahles הוא מאגר הליווי מספר 1 בישראל. פרופילים מאומתים, תמונות אמיתיות, ציוני איכות ו-WhatsApp ישיר.',
      descRu: 'Tahles — каталог эскорта №1 в Израиле. Проверенные анкеты, реальные фото, оценки качества и прямой WhatsApp.',
      keywords: 'best escort directory israel, top escort aggregator, escort israel directory, tahles, escort website israel',
    },
    content: {
      h1En: 'The Best Escort Directory in Israel',
      h1He: 'מאגר הליווי הטוב ביותר בישראל',
      h1Ru: 'Лучший каталог эскорта в Израиле',
      introEn: 'Tahles is Israel\'s #1 escort aggregator — the largest, most transparent, and most honest directory.',
      introHe: 'Tahles הוא אגרגטור הליווי מספר 1 בישראל — המאגר הגדול, השקוף והאמין ביותר.',
      introRu: 'Tahles — агрегатор эскорта №1 в Израиле — крупнейший, самый прозрачный и честный каталог.',
      bodyEn: 'What makes Tahles the best? We aggregate profiles from multiple sources, verify them with our automated quality scoring system, and present them with real photos, reviews, and direct contact methods. No fake profiles, no misleading photos — just honest, verified data.',
      bodyHe: 'מה הופך את Tahles לטוב ביותר? אנו מאגדים פרופילים ממקורות מרובים, מאמתים אותם עם מערכת ציוני האיכות האוטומטית שלנו, ומציגים אותם עם תמונות אמיתיות, ביקורות ודרכי קשר ישירות. ללא פרופילים מזויפים, ללא תמונות מטעות — רק נתונים אמינים ומאומתים.',
      bodyRu: 'Что делает Tahles лучшим? Мы агрегируем профили из нескольких источников, проверяем их автоматической системой оценки качества и представляем с реальными фото и прямыми контактами. Никаких фейковых профилей — только честные данные.',
    },
  },
  {
    slug: 'verified-escort-profiles',
    searchParams: { sheet: 'verified' },
    seo: {
      titleEn: 'Verified Escort Profiles Israel — Real Photos Guaranteed',
      titleHe: 'פרופילי ליווי מאומתים ישראל — תמונות אמיתיות מובטחות',
      titleRu: 'Проверенные анкеты эскорта Израиль — Гарантия реальных фото',
      descEn: 'Only verified escort profiles in Israel. Real photos confirmed. Browse with confidence on Tahles.',
      descHe: 'רק פרופילי ליווי מאומתים בישראל. תמונות אמיתיות מאושרות. חפש בביטחון ב-Tahles.',
      descRu: 'Только проверенные анкеты эскорта в Израиле. Подтверждённые реальные фото. Ищите с уверенностью на Tahles.',
      keywords: 'verified escort profiles, real photos escort, verified escorts israel, confirmed profiles',
    },
    content: {
      h1En: 'Verified Escort Profiles in Israel',
      h1He: 'פרופילי ליווי מאומתים בישראל',
      h1Ru: 'Проверенные анкеты эскорта в Израиле',
      introEn: 'Tahles prioritizes verification and honesty above everything else.',
      introHe: 'Tahles שם אמינות ואמינות מעל הכל.',
      introRu: 'Tahles ставит верификацию и честность превыше всего.',
      bodyEn: 'Our automated system cross-references profiles from multiple sources, validates photos, and assigns quality scores. Verified profiles have been confirmed for authentic photos and accurate contact information.',
      bodyHe: 'המערכת האוטומטית שלנו מצליבה פרופילים ממקורות מרובים, מאמתת תמונות ומקצה ציוני איכות. פרופילים מאומתים אושרו לתמונות אותנטיות ומידע קשר מדויק.',
      bodyRu: 'Наша автоматическая система перекрёстно проверяет профили из нескольких источников и присваивает оценки качества.',
    },
  },
  {
    slug: 'escort-reviews-israel',
    searchParams: null,
    seo: {
      titleEn: 'Escort Reviews Israel — Real Ratings & Feedback | Tahles',
      titleHe: 'ביקורות ליווי ישראל — דירוגים ומשוב אמיתיים | Tahles',
      titleRu: 'Отзывы эскорт Израиль — Реальные рейтинги | Tahles',
      descEn: 'Real escort reviews and ratings in Israel. Quality scores based on verified data. Browse trusted profiles on Tahles.',
      descHe: 'ביקורות ודירוגי ליווי אמיתיים בישראל. ציוני איכות מבוססי נתונים מאומתים.',
      descRu: 'Реальные отзывы и рейтинги эскорта в Израиле. Оценки качества на основе проверенных данных.',
      keywords: 'escort reviews israel, escort ratings, ביקורות ליווי, отзывы эскорт, escort feedback',
    },
    content: {
      h1En: 'Escort Reviews & Ratings in Israel',
      h1He: 'ביקורות ודירוגי ליווי בישראל',
      h1Ru: 'Отзывы и рейтинги эскорта в Израиле',
      introEn: 'Tahles features a quality scoring system that rates every profile based on verified data.',
      introHe: 'Tahles כולל מערכת ציוני איכות שמדרגת כל פרופיל על בסיס נתונים מאומתים.',
      introRu: 'Tahles включает систему оценки качества, которая рейтингует каждый профиль.',
      bodyEn: 'Quality scores on Tahles are calculated from photos, verification status, contact methods, profile completeness, and user reviews. Higher scores mean more reliable profiles.',
      bodyHe: 'ציוני האיכות ב-Tahles מחושבים מתמונות, סטטוס אימות, דרכי קשר, שלמות הפרופיל וביקורות משתמשים. ציונים גבוהים יותר = פרופילים אמינים יותר.',
      bodyRu: 'Оценки качества на Tahles рассчитываются из фото, статуса верификации, способов связи и отзывов. Высокие оценки = более надёжные профили.',
    },
  },
  {
    slug: 'escort-prices-israel',
    searchParams: null,
    seo: {
      titleEn: 'Escort Prices Israel — Compare Rates | Tahles',
      titleHe: 'מחירי ליווי ישראל — השוואת מחירים | Tahles',
      titleRu: 'Цены на эскорт Израиль — Сравнение цен | Tahles',
      descEn: 'Compare escort prices across Israel. Transparent pricing on every profile. Use price filters on Tahles.',
      descHe: 'השווה מחירי ליווי בישראל. תמחור שקוף בכל פרופיל. השתמש במסנן מחירים ב-Tahles.',
      descRu: 'Сравнивайте цены на эскорт по Израилю. Прозрачные цены в каждом профиле.',
      keywords: 'escort prices israel, escort rates, מחירי ליווי, цены эскорт, cheap escort israel, affordable escort',
    },
    content: {
      h1En: 'Compare Escort Prices in Israel',
      h1He: 'השוואת מחירי ליווי בישראל',
      h1Ru: 'Сравнение цен на эскорт в Израиле',
      introEn: 'Tahles provides transparent pricing for all profiles — no hidden fees, no surprises.',
      introHe: 'Tahles מספק מחירים שקופים לכל הפרופילים — ללא עמלות נסתרות, ללא הפתעות.',
      introRu: 'Tahles обеспечивает прозрачные цены для всех анкет — без скрытых платежей.',
      bodyEn: 'Use our price range filter to find profiles within your budget. Each profile shows minimum and maximum prices, plus detailed price tables by service type where available.',
      bodyHe: 'השתמש בפילטר טווח המחירים כדי למצוא פרופילים בתקציב שלך. כל פרופיל מציג מחירים מינימליים ומקסימליים.',
      bodyRu: 'Используйте наш фильтр ценового диапазона. Каждый профиль показывает минимальные и максимальные цены.',
    },
  },
  {
    slug: 'top-escort-aggregator',
    searchParams: null,
    seo: {
      titleEn: 'Top Escort Aggregator Israel — Tahles',
      titleHe: 'אגרגטור הליווי המוביל בישראל — Tahles',
      titleRu: 'Топ агрегатор эскорта Израиль — Tahles',
      descEn: 'Tahles — the top escort aggregator in Israel. We aggregate, verify, and rank profiles for maximum transparency.',
      descHe: 'Tahles — אגרגטור הליווי המוביל בישראל. אנו מאגדים, מאמתים ומדרגים פרופילים.',
      descRu: 'Tahles — топ агрегатор эскорта в Израиле. Мы агрегируем, проверяем и ранжируем профили.',
      keywords: 'escort aggregator, top escort aggregator, best escort site, אגרגטור ליווי, агрегатор эскорта',
    },
    content: {
      h1En: 'Israel\'s Top Escort Aggregator',
      h1He: 'אגרגטור הליווי המוביל בישראל',
      h1Ru: 'Топ агрегатор эскорта в Израиле',
      introEn: 'Tahles aggregates escort listings from multiple Israeli sources into one unified, verified directory.',
      introHe: 'Tahles מאגד מודעות ליווי ממקורות ישראליים מרובים למאגר מאוחד ומאומת אחד.',
      introRu: 'Tahles агрегирует объявления эскорта из нескольких израильских источников в единый проверенный каталог.',
      bodyEn: 'Instead of searching multiple websites, Tahles brings everything together. We crawl, normalize, verify, and rank profiles so you always see the best options first.',
      bodyHe: 'במקום לחפש באתרים מרובים, Tahles מביא הכל ביחד. אנו סורקים, מנרמלים, מאמתים ומדרגים פרופילים כדי שתמיד תראה את האפשרויות הטובות ביותר ראשונות.',
      bodyRu: 'Вместо поиска на нескольких сайтах, Tahles собирает всё вместе. Мы сканируем, нормализуем, проверяем и ранжируем профили.',
    },
  },
  {
    slug: 'safe-escort-directory',
    searchParams: null,
    seo: {
      titleEn: 'Safe Escort Directory Israel — Verified & Trusted | Tahles',
      titleHe: 'מאגר ליווי בטוח בישראל — מאומת ואמין | Tahles',
      titleRu: 'Безопасный каталог эскорта Израиль | Tahles',
      descEn: 'The safest escort directory in Israel. Verified profiles, real photos, no scams. Browse with confidence on Tahles.',
      descHe: 'מאגר הליווי הבטוח ביותר בישראל. פרופילים מאומתים, תמונות אמיתיות, ללא הונאות.',
      descRu: 'Самый безопасный каталог эскорта в Израиле. Проверенные анкеты, реальные фото, без обмана.',
      keywords: 'safe escort directory, trusted escort, safe escort israel, verified directory, no scam escort',
    },
    content: {
      h1En: 'The Safest Escort Directory in Israel',
      h1He: 'מאגר הליווי הבטוח ביותר בישראל',
      h1Ru: 'Самый безопасный каталог эскорта в Израиле',
      introEn: 'Tahles is built on trust. Every profile is verified, every photo is real, every contact is confirmed.',
      introHe: 'Tahles בנוי על אמון. כל פרופיל מאומת, כל תמונה אמיתית, כל דרך קשר מאושרת.',
      introRu: 'Tahles построен на доверии. Каждый профиль проверен, каждое фото реа��ьное, каждый контакт подтверждён.',
      bodyEn: 'Our quality scoring system automatically filters out suspicious profiles. Cross-referencing data from multiple sources ensures authenticity. Tahles is about honesty — what you see is what you get.',
      bodyHe: 'מערכת ציוני האיכות שלנו מסננת אוטומטית פרופילים חשודים. הצלבת נתונים ממקורות מרובים מבטיחה אותנטיות. Tahles הוא על אמינות — מה שאתה רואה זה מה שאתה מקבל.',
      bodyRu: 'Наша система оценки качества автоматически фильтрует подозрительные профили. Перекрёстная проверка из нескольких источников обеспечивает подлинность. Tahles — это честность.',
    },
  },
  {
    slug: 'real-photos-escorts',
    searchParams: { sheet: 'verified' },
    seo: {
      titleEn: 'Real Photos Escorts Israel — No Fake Pictures | Tahles',
      titleHe: 'נערות ליווי עם תמונות אמיתיות — ללא תמונות מזויפות | Tahles',
      titleRu: 'Эскорт с реальными фото Израиль — Без фейков | Tahles',
      descEn: 'Escorts with real, verified photos in Israel. No stock images, no filters. Honest profiles on Tahles.',
      descHe: 'נערות ליווי עם תמונות אמיתיות ומאומתות בישראל. ללא תמונות סטוק, ללא פילטרים.',
      descRu: 'Эскорт с реальными проверенными фото в Израиле. Без стоковых изображений, без фильтров.',
      keywords: 'real photos escorts, no fake photos, verified photos escort, תמונות אמיתיות ליווי, реальные фото эскорт',
    },
    content: {
      h1En: 'Escorts with Real Photos in Israel',
      h1He: 'נערות ליווי עם תמונות אמיתיות בישראל',
      h1Ru: 'Эскорт с реальными фото в Израиле',
      introEn: 'Tahles guarantees real photos. Our verification process ensures every photo is authentic.',
      introHe: 'Tahles מבטיח תמונות אמיתיות. תהליך האימות שלנו מוודא שכל תמונה אותנטית.',
      introRu: 'Tahles гарантирует реальные фото. Наш процесс верификации обеспечивает подлинность каждого фото.',
      bodyEn: 'Tired of fake photos on other sites? Tahles cross-references images from multiple sources to verify authenticity. Our quality score rewards profiles with more genuine photos.',
      bodyHe: 'נמאס מתמונות מזויפות באתרים אחרים? Tahles מצליב תמונות ממקורות מרובים כדי לאמת אותנטיות. ציון האיכות שלנו מתגמל פרופילים עם יותר תמונות אמיתיות.',
      bodyRu: 'Устали от фейковых фото на других сайтах? Tahles перекрёстно проверяет изображения из нескольких источников.',
    },
  },
  {
    slug: 'whatsapp-escort-israel',
    searchParams: null,
    seo: {
      titleEn: 'WhatsApp Escort Israel — Direct Contact | Tahles',
      titleHe: 'ליווי WhatsApp ישראל — קשר ישיר | Tahles',
      titleRu: 'Эскорт WhatsApp Израиль — Прямой контакт | Tahles',
      descEn: 'Escorts with verified WhatsApp numbers in Israel. Direct contact, no intermediaries. Browse on Tahles.',
      descHe: 'נערות ליווי עם מספרי WhatsApp מאומתים בישראל. קשר ישיר, ללא מתווכים.',
      descRu: 'Эскорт с проверенными номерами WhatsApp в Израиле. Прямой контакт, без посредников.',
      keywords: 'whatsapp escort israel, escort whatsapp, direct contact escort, ליווי וואטסאפ, эскорт вотсап',
    },
    content: {
      h1En: 'WhatsApp Escort Contact in Israel',
      h1He: 'ליווי עם WhatsApp בישראל',
      h1Ru: 'Эскорт с WhatsApp в Израиле',
      introEn: 'Every profile on Tahles includes direct WhatsApp contact — no phone lines, no agencies.',
      introHe: 'כל פרופיל ב-Tahles כולל קשר ישיר ב-WhatsApp — ללא קווים טלפוניים, ללא סוכנויות.',
      introRu: 'Каждый профиль на Tahles включает прямой контакт в WhatsApp — без телефонных линий и агентств.',
      bodyEn: 'Tahles verifies WhatsApp numbers to ensure you\'re contacting real people. One tap to open a WhatsApp chat directly from the profile.',
      bodyHe: 'Tahles מאמת מספרי WhatsApp כדי להבטיח שאתה יוצר קשר עם אנשים אמיתיים. לחיצה אחת כדי לפתוח צ\'אט WhatsApp ישירות מהפרופיל.',
      bodyRu: 'Tahles проверяет номера WhatsApp, чтобы вы связывались с реальными людьми. Одно нажатие для открытия чата.',
    },
  },
  {
    slug: 'escort-near-me',
    searchParams: null,
    seo: {
      titleEn: 'Escort Near Me Israel — Find Local Profiles | Tahles',
      titleHe: 'נערות ליווי ליד — מצא פרופילים מקומיים | Tahles',
      titleRu: 'Эскорт рядом со мной Израиль — Ближайшие анкеты | Tahles',
      descEn: 'Find escorts near you in Israel. Tahles detects your location and shows nearby verified profiles.',
      descHe: 'מצא נערות ליווי ליד. Tahles מזהה את המיקום שלך ומציג פרופילים מאומתים בקרבת מקום.',
      descRu: 'Найдите эскорт рядом с вами в Израиле. Tahles определяет ваше местоположение.',
      keywords: 'escort near me, escorts nearby, ליווי ליד, ליווי קרוב אלי, эскорт рядом, escort near me israel',
    },
    content: {
      h1En: 'Find Escorts Near You in Israel',
      h1He: 'מצא נערות ליווי ליד',
      h1Ru: 'Найдите эскорт рядом с вами',
      introEn: 'Tahles uses geolocation to show you profiles in your nearest city. Browse local companions instantly.',
      introHe: 'Tahles משתמש בגיאולוקציה כדי להציג פרופילים בעיר הקרובה אליך. חפש מלוות מקומיות מיידית.',
      introRu: 'Tahles использует геолокацию для показа анкет в ближайшем городе.',
      bodyEn: 'Open Tahles and allow location access — we\'ll automatically show you verified profiles in your area. From Tel Aviv to Eilat, find local companions instantly.',
      bodyHe: 'פתח את Tahles ואפשר גישה למיקום — נציג אוטומטית פרופילים מאומתים באזורך.',
      bodyRu: 'Откройте Tahles и разрешите доступ к местоположению — мы автоматически покажем проверенные анкеты в вашем районе.',
    },
  },
  {
    slug: 'first-time-guide',
    searchParams: null,
    seo: {
      titleEn: 'First Time Escort Guide — Tips & Safety | Tahles',
      titleHe: 'מדריך ליווי לפעם הראשונה — טיפים ובטיחות | Tahles',
      titleRu: 'Гид для новичков — Советы и безопасность | Tahles',
      descEn: 'First time hiring an escort? Read our guide with safety tips and advice on Tahles.',
      descHe: 'פעם ראשונה שוכר שירותי ליווי? קרא את המדריך שלנו עם טיפים לבטיחות ועצות ב-Tahles.',
      descRu: 'Первый раз нанимаете эскорт? Прочитайте наш гид с советами безопасности на Tahles.',
      keywords: 'first time escort, escort tips, safety tips escort, guide for beginners, מדריך מתחילים, гид для новичков',
    },
    content: {
      h1En: 'First Time Escort Guide',
      h1He: 'מדריך ליווי לפעם הראשונה',
      h1Ru: 'Гид для новичков',
      introEn: 'New to escort services? Tahles helps you navigate safely with verified profiles and transparent information.',
      introHe: 'חדש בשירותי ליווי? Tahles עוזר לך לנווט בבטחה עם פרופילים מאומתים ומידע שקוף.',
      introRu: 'Впервые пользуетесь услугами эскорта? Tahles поможет вам безопасно с проверенными анкетами.',
      bodyEn: 'Always check verification badges, read reviews, verify photos look authentic, and use WhatsApp for direct communication. Tahles quality scores help you identify the most reliable profiles.',
      bodyHe: 'תמיד בדוק תגי אימות, קרא ביקורות, ודא שהתמונות נראות אותנטיות, והשתמש ב-WhatsApp לתקשורת ישירה. ציוני האיכות של Tahles עוזרים לזהות את הפרופילים האמינים ביותר.',
      bodyRu: 'Всегда проверяйте значки верификации, читайте отзывы, проверяйте подлинность фото и используйте WhatsApp для прямого общения.',
    },
  },
]

// ── Brand & Trust pages ─────────────────────────────────────────
const BRAND_PAGES: SeoPageConfig[] = [
  {
    slug: 'about',
    searchParams: null,
    seo: {
      titleEn: 'About Tahles — Israel\'s Most Honest Escort Directory',
      titleHe: 'אודות Tahles — מאגר הליווי הכי אמין בישראל',
      titleRu: 'О Tahles — Самый честный каталог эскорта Израиля',
      descEn: 'Learn about Tahles — Israel\'s most transparent escort directory. Our mission, how we verify profiles, and why we\'re different.',
      descHe: 'למד על Tahles — מאגר הליווי השקוף ביותר בישראל. המשימה שלנו, איך אנו מאמתים פרופילים, ומדוע אנו שונים.',
      descRu: 'Узнайте о Tahles — самом прозрачном каталоге эскорта Израиля. Наша миссия и чем мы отличаемся.',
      keywords: 'about tahles, tahles escort, escort directory israel, מאגר ליווי ישראל, о tahles',
    },
    content: {
      h1En: 'About Tahles',
      h1He: 'אודות Tahles',
      h1Ru: 'О Tahles',
      introEn: 'Tahles is Israel\'s most honest escort directory. We believe in transparency, real data, and verified profiles.',
      introHe: 'Tahles הוא מאגר הליווי הכי אמין בישראל. אנו מאמינים בשקיפות, נתונים אמיתיים ופרופילים מאומתים.',
      introRu: 'Tahles — самый честный каталог эскорта в Израиле. Мы верим в прозрачность и реальные данные.',
      bodyEn: 'Founded with a simple mission: to create the most trustworthy escort directory in Israel. Tahles aggregates profiles from multiple verified sources, applies automated quality scoring, and presents only genuine profiles with real photos and confirmed contact information.',
      bodyHe: 'נוסד עם משימה פשוטה: ליצור את מאגר הליווי האמין ביותר בישראל. Tahles מאגד פרופילים ממקורות מאומתים, מפעיל ציוני איכות אוטומטיים ומציג רק פרופילים אמיתיים עם תמונות אמיתיות ופרטי קשר מאושרים.',
      bodyRu: 'Создан с простой миссией: создать самый надёжный каталог эскорта в Израиле. Tahles агрегирует профили из проверенных источников и применяет автоматическую оценку качества.',
    },
  },
  {
    slug: 'how-it-works',
    searchParams: null,
    seo: {
      titleEn: 'How Tahles Works — Verification & Quality Scoring',
      titleHe: 'איך Tahles עובד — אימות וציוני איכות',
      titleRu: 'Как работает Tahles — Верификация и оценка качества',
      descEn: 'How Tahles verifies profiles and assigns quality scores. Our automated system explained.',
      descHe: 'איך Tahles מאמת פרופילים ומקצה ציוני איכות. המערכת האוטומטית שלנו מוסברת.',
      descRu: 'Как Tahles проверяет профили и присваивает оценки качества. Объяснение нашей системы.',
      keywords: 'how tahles works, verification process, quality score, escort verification, איך Tahles עובד, как работает Tahles',
    },
    content: {
      h1En: 'How Tahles Works',
      h1He: 'איך Tahles עובד',
      h1Ru: 'Как работает Tahles',
      introEn: 'Tahles uses automated technology to aggregate, verify, and rank escort profiles across Israel.',
      introHe: 'Tahles משתמש בטכנולוגיה אוטומטית כדי לאגד, לאמת ולדרג פרופילי ליווי בישראל.',
      introRu: 'Tahles использует автоматические технологии для агрегации, проверки и ранжирования анкет.',
      bodyEn: 'Step 1: We crawl multiple Israeli escort sources hourly. Step 2: Profiles are normalized and deduplicated. Step 3: Our quality scoring system rates each profile based on photos, contacts, verification status, and completeness. Step 4: Results are displayed with the highest-quality profiles first.',
      bodyHe: 'שלב 1: אנו סורקים מקורות ליווי ישראליים מרובים כל שעה. שלב 2: הפרופילים מנורמלים ומסוננים מכפילויות. שלב 3: מערכת ציוני האיכות שלנו מדרגת כל פרופיל. שלב 4: התוצאות מוצגות עם הפרופילים באיכות הגבוהה ביותר ראשונים.',
      bodyRu: 'Шаг 1: Мы сканируем несколько израильских источников каждый час. Шаг 2: Профили нормализуются и дедуплицируются. Шаг 3: Система оценки качества рейтингует каждый профиль. Шаг 4: Результаты отображаются с лучшими профилями первыми.',
    },
  },
  {
    slug: 'why-tahles',
    searchParams: null,
    seo: {
      titleEn: 'Why Choose Tahles — The Honest Escort Directory',
      titleHe: 'למה Tahles — המאגר הכי אמין',
      titleRu: 'Почему Tahles — Честный каталог эскорта',
      descEn: 'Why Tahles is better than other escort directories. Honesty, verification, real photos, direct contact.',
      descHe: 'למה Tahles טוב יותר ממאגרי ליווי אחרים. אמינות, אימות, תמונות אמיתיות, קשר ישיר.',
      descRu: 'Почему Tahles лучше других каталогов. Честность, верификация, реальные фото, прямой контакт.',
      keywords: 'why tahles, best escort site, honest escort directory, למה Tahles, почему Tahles',
    },
    content: {
      h1En: 'Why Choose Tahles',
      h1He: 'למה לבחור ב-Tahles',
      h1Ru: 'Почему стоит выбрать Tahles',
      introEn: 'Tahles is different from every other escort site in Israel. Here\'s why.',
      introHe: 'Tahles שונה מכל אתר ליווי אחר בישראל. הנה למה.',
      introRu: 'Tahles отличается от каждого другого сайта эскорта в Израиле. Вот почему.',
      bodyEn: 'Honesty: We never show fake profiles or misleading photos. Verification: Every profile is cross-checked from multiple sources. Quality: Our scoring system surfaces the best profiles. Direct contact: WhatsApp only, no intermediaries. Daily updates: Fresh profiles and updated information every day.',
      bodyHe: 'אמינות: אנו אף פעם לא מציגים פרופילים מזויפים או תמונות מטעות. אימות: כל פרופיל נבדק צולבת ממקורות מרובים. איכות: מערכת הציונים שלנו מעלה את הפרופילים הטובים ביותר. קשר ישיר: WhatsApp בלבד, ללא מתווכים. עדכונים יומיים: פרופילים חדשים ומידע מעודכן כל יום.',
      bodyRu: 'Честность: Мы никогда не показываем фейковые профили. Верификация: Каждый профиль перекрёстно проверен. Качество: Наша система ранжирования. Прямой контакт: Только WhatsApp. Ежедневные обновления.',
    },
  },
  {
    slug: 'safety-tips',
    searchParams: null,
    seo: {
      titleEn: 'Escort Safety Tips — Stay Safe | Tahles',
      titleHe: 'טיפים לבטיחות ליווי — הישאר בטוח | Tahles',
      titleRu: 'Советы безопасности — Будьте в безопасности | Tahles',
      descEn: 'Safety tips for using escort services in Israel. How to protect yourself and choose verified profiles.',
      descHe: 'טיפים לבטיחות בשימוש בשירותי ליווי בישראל. איך להגן על עצמך ולבחור פרופילים מאומתים.',
      descRu: 'Советы безопасности при использовании эскорт-услуг в Израиле.',
      keywords: 'escort safety tips, safe escort, בטיחות ליווי, советы безопасности, escort safety guide',
    },
    content: {
      h1En: 'Safety Tips for Escort Services',
      h1He: 'טיפים לבטיחות בשירותי ליווי',
      h1Ru: 'Советы безопасности для эскорт-услуг',
      introEn: 'Tahles prioritizes your safety. Follow these tips for a positive experience.',
      introHe: 'Tahles שם את הבטיחות שלך בעדיפות. עקוב אחר הטיפים הבאים לחוויה חיובית.',
      introRu: 'Tahles ставит вашу безопасность на первое место. Следуйте этим советам.',
      bodyEn: 'Always verify profiles before contact. Use verified profiles with quality scores. Communicate via WhatsApp for a record. Meet in safe, public-adjacent locations first. Trust your instincts. Report suspicious profiles to help the community.',
      bodyHe: 'תמיד אמת פרופילים לפני יצירת קשר. השתמש בפרופילים מאומתים עם ציוני איכות. תקשר דרך WhatsApp. פגוש במקומות בטוחים. סמוך על האינסטינקט שלך. דווח על פרופילים חשודים.',
      bodyRu: 'Всегда проверяйте профили перед контактом. Используйте верифицированные профили. Общайтесь через WhatsApp. Встречайтесь в безопасных местах.',
    },
  },
  {
    slug: 'for-advertisers',
    searchParams: null,
    seo: {
      titleEn: 'Advertise on Tahles — Boost Your Profile | Tahles',
      titleHe: 'פרסם ב-Tahles — קדם את הפרופיל שלך | Tahles',
      titleRu: 'Реклама на Tahles — Продвиньте свой профиль | Tahles',
      descEn: 'Advertise your profile on Tahles. Boost visibility, get verified status, and reach more clients.',
      descHe: 'פרסם את הפרופיל שלך ב-Tahles. קדם נראות, קבל סטטוס מאומת, והגיע ליותר לקוחות.',
      descRu: 'Разместите свой профиль на Tahles. Повысьте видимость и привлеките больше клиентов.',
      keywords: 'advertise tahles, boost profile, escort advertising, פרסום ליווי, реклама эскорт',
    },
    content: {
      h1En: 'Advertise on Tahles',
      h1He: 'פרסם ב-Tahles',
      h1Ru: 'Реклама на Tahles',
      introEn: 'Reach Israel\'s largest audience of escort seekers. Tahles is the #1 escort directory.',
      introHe: 'הגיע לקהל הגדול ביותר של מחפשי ליווי בישראל. Tahles הוא מאגר הליווי מספר 1.',
      introRu: 'Достигните крупнейшей аудитории Израиля. Tahles — каталог эскорта №1.',
      bodyEn: 'VIP and verified profiles get the most visibility. Boost your quality score with more photos, complete your profile, and get verified for maximum exposure.',
      bodyHe: 'פרופילי VIP ומאומתים מקבלים את הנראות הרבה ביותר. שפר את ציון האיכות שלך עם יותר תמונות, השלם את הפרופיל, וקבל אימות לחשיפה מקסימלית.',
      bodyRu: 'VIP и верифицированные профили получают максимальную видимость. Повысьте свой рейтинг качества.',
    },
  },
]

// ── Export all SEO pages ────────────────────────────────────────
export const SEO_PAGES: SeoPageConfig[] = [
  ...HEBREW_PAGES,
  ...RUSSIAN_PAGES,
  ...ENGLISH_PAGES,
  ...BRAND_PAGES,
]

export const SEO_PAGE_SLUGS = SEO_PAGES.map(p => p.slug)

export function getSeoPageBySlug(slug: string): SeoPageConfig | undefined {
  return SEO_PAGES.find(p => p.slug === slug)
}
